config/routes.rb
Rails.application.routes.draw do

  get 'post/index'

  namespace :admin do
    resources :categories
    resources :labels
    resources :posts
    resources :home, only: [:index]
  end

  devise_for :users
  get 'themes/tipo'
  get 'themes/buttons'
  get 'themes/form'
  get 'themes/hyperlink'
  get 'themes/index'
  # You can have the root of your site routed with "root"
  root 'home#index'

  resources :posts, only: [:show] do
    resources :comments, only: [:create]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :nombre_categoria, presence: true
  validates :nombre_categoria, uniqueness: true

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :category
  has_many :posts, through: :post_has_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :comentario, presence: true
    belongs_to :posts
end

app/models/label.rb
class Label < ActiveRecord::Base
  validates :nombre_etiqueta, presence: true
  validates :nombre_etiqueta, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :titulo,:contenido, presence: true
  validates :titulo,:contenido, uniqueness: true

  belongs_to :user

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :post
  has_many :categories, through: :post_has_categories

  has_many :comments, dependent: :destroy
end

app/models/post_has_category.rb
class PostHasCategory < ActiveRecord::Base
  belongs_to :post, :inverse_of => :post_has_categories
  belongs_to :category, :inverse_of => :post_has_categories

  validates_presence_of :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  validates :nombre, presence: true
  validates :apellidoPaterno, presence: true
  validates :apellidoMaterno, presence: true

  has_many :posts

  def nombre_usuario
    "#{nombre} #{apellidoPaterno} #{apellidoMaterno}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource
  private
    def after_sign_in_path_for(resourse)
        admin_home_index_path
    end

  protected
    def layout_by_resource
      if devise_controller?
        "login"
      else
        "application"
      end
    end
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :email, :password, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento] )
        devise_parameter_sanitizer.permit(:sign_in, keys: [:nombre, :email, :password, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento] )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
        params.require(:comment).permit(:nombre_completo, :comentario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :set_categories

  def tipo
  end

  def form
  end

  def buttons
  end

  def hyperlink
  end

  private
    def set_categories
      @categories = Category.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def label_params
      params.require(:user).permit(:nombre, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento)
    end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML

    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
    <ul> LOOKS LIKE THAT YOU WAS WRONG IN SOME FIELD :(  </ul>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_sidebar_theme.html.erb
<div class="admin-sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li <%= 'class=active' if params[:action] == 'tipo' %> ><%= link_to "Tipografias", themes_tipo_path %></li>
    <li <%= 'class=active' if params[:action] == 'buttons' %> ><%= link_to "Botones", themes_buttons_path %></li>
    <li <%= 'class=active' if params[:action] == 'form' %> ><%= link_to "Formularios", themes_form_path %></li>
    <li <%= 'class=active' if params[:action] == 'hyperlink' %> ><%= link_to "Hipervinculos", themes_hyperlink_path %></li>
  </ul>
</div>

app/views/themes/buttons.html.erb
<!-- Navbar -->
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
  <%= render 'sidebar_theme' %>
</div>

<!-- Content -->
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">

  <div class="bg-white">

    <div class="encabezado text-center">Botones</div>

    <div class="container-fluid">
      <div class="row">

        <!-- Columna 1 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Estilo 1</h3>
          <a class="estilo_btn1 btn-block">Estilo 1 (.estilo_btn1)</a>
          <a href="#" class="btn btn1_disabled btn-block disabled"> Boton Desactivado</a>
        </div>

        <!-- Columna 2 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Estilo 2</h3>
          <a class="estilo_btn2 btn-block">Estilo 2 (.estilo_btn2)</a>
          <a href="#" class="btn btn2_disabled btn-block disabled"> Boton Desactivado</a>
        </div>

        <!-- Columna 3 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Estilo 3</h3>
          <a class="estilo_btn3 btn-block">Estilo 3 (.estilo_btn3)</a>
          <a href="#" class="btn btn3_disabled btn-block disabled"> Boton Desactivado</a>
        </div>

        <!-- Columna 3 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Estilo 4</h3>
          <p><i class="fa fa-spinner fa-spin fa-fw"></i> Proximamente...</p>
        </div>

      </div>

      <div class="row">

        <!-- Columna 1 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Grande</h3>
          <a class="estilo_btn1 btn-block st-lg">Grande (.st-lg)</a>
          <a href="#" class="btn btn1_disabled btn-block disabled st-lg"> Boton Desactivado</a>

          <h3 class="text-center">Chico</h3>
          <a class="estilo_btn1 btn-block st-sm">Grande (.st-sm)</a>
          <a href="#" class="btn btn1_disabled btn-block disabled st-sm"> Boton Desactivado</a>

          <h3 class="text-center">Extra chico</h3>
          <a class="estilo_btn1 btn-block st-xs">Grande (.st-xs)</a>
          <a href="#" class="btn btn1_disabled btn-block disabled st-xs"> Boton Desactivado</a>
        </div>

        <!-- Columna 2 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Grande</h3>
          <a class="estilo_btn2 btn-block st-lg">Grande</a>
          <a href="#" class="btn btn2_disabled btn-block disabled st-lg"> Boton Desactivado</a>

          <h3 class="text-center">Chico</h3>
          <a class="estilo_btn2 btn-block st-sm">Grande (.st-sm)</a>
          <a href="#" class="btn btn2_disabled btn-block disabled st-sm"> Boton Desactivado</a>

          <h3 class="text-center">Extra chico</h3>
          <a class="estilo_btn2 btn-block st-xs">Grande (.st-xs)</a>
          <a href="#" class="btn btn2_disabled btn-block disabled st-xs"> Boton Desactivado</a>
        </div>

        <!-- Columna 2 -->
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <h3 class="text-center">Grande</h3>
          <a class="estilo_btn3 btn-block st-lg">Grande</a>
          <a href="#" class="btn btn3_disabled btn-block disabled st-lg"> Boton Desactivado</a>

          <h3 class="text-center">Chico</h3>
          <a class="estilo_btn3 btn-block st-sm">Grande (.st-sm)</a>
          <a href="#" class="btn btn3_disabled btn-block disabled st-sm"> Boton Desactivado</a>

          <h3 class="text-center">Extra chico</h3>
          <a class="estilo_btn3 btn-block st-xs">Grande (.st-xs)</a>
          <a href="#" class="btn btn3_disabled btn-block disabled st-xs"> Boton Desactivado</a>
        </div>

      </div>

    </div>

  </div>

</div>

app/views/themes/form.html.erb
<!-- Navbar -->
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
  <%= render 'sidebar_theme' %>
</div>

<!-- Content -->
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
	<div class="bg-white">

		<div class="container-fluid">
			<div class="row">

				<!-- Parte Derecha -->
				<div class="col-md-6">
					<h4>Formulario Horizontal</h4>
					<form action="#" class="form-horizontal custom-form">

						<div class="form-group">
							<div class="col-md-12">
								<div class="search-white">
					        <label><i class="fa fa-search"></i></label>
					        <input class="form-control" placeholder="Buscar...">
					      </div>
							</div>
						</div>

			      <div class="form-group">
			      	<div class="col-md-6"><input type="text" class="form-control" placeholder="Ingresar Texto"></div>
			      	<div class="col-md-6"><input type="text" class="form-control" disabled="disabled" value="Desactivado"></div>
			      </div>

			      <div class="form-group">
			      	<div class="col-md-12">
			      		<select class="form-control">
			      			<option value="0">- Seleccionar -</option>
			      			<option value="1">Ingenieria de Software</option>
			      			<option value="2">Computo de alto desempeño</option>
			      		</select>
			      	</div>
			      </div>

			      <div class="from-group">
		      		<div class="checkbox-inline">
							  <label><input type="checkbox" value="">Ingeniería</label>
							</div>
							<div class="checkbox-inline">
							  <label><input type="checkbox">Computo alto desempeño</label>
							</div>
			      </div>

			      <div class="form-group">
			      	<div class="col-md-12">

			      		<div class="radio-inline">
								  <label><input type="radio" name="optionsRadios" checked> Ingeniería</label>
								</div>
								<div class="radio-inline">
								  <label><input type="radio" name="optionsRadios">Computo alto desempeño</label>
								</div>

			      	</div>
			      </div>

					</form>
				</div>

				<!-- Parte Izquierda -->
				<div class="col-md-6">
					<h4>Formulario Vertical</h4>
					<form action="#" class="custom-form">

						<div class="form-group">
					    <label>Nombre del campo:</label>
					    <input type="text" class="form-control" placeholder="Ingresar Texto">
					  </div>

					  <div class="form-group">
					    <label>Nombre del campo:</label>
					    <textarea rows="5" class="form-control"></textarea>
					  </div>

					  <div class="checkbox">
						  <label><input type="checkbox" value="">Ingeniería</label>
						</div>
						<div class="checkbox">
						  <label><input type="checkbox">Computo alto desempeño</label>
						</div>

						<div class="radio">
						  <label><input type="radio" name="optionsRadios" checked> Ingeniería</label>
						</div>
						<div class="radio">
						  <label><input type="radio" name="optionsRadios">Computo alto desempeño</label>
						</div>

					</form>
				</div>
			</div>
		</div>

	</div>
</div>

app/views/themes/hyperlink.html.erb
<!-- Navbar -->
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
  <%= render 'sidebar_theme' %>
</div>

<!-- Content -->
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
    <div class="bg-white">

        <div class="container-fluid">
          <div class="row">
            <!-- Columna 1 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 1 (.cl-effect-1)</h3>
                <a href="#" class="cl-effect-1 color-blue">Leer más ...</a>
                <a href="#" class="cl-effect-1 color-green">Leer más ...</a>
                <a href="#" class="cl-effect-1 color-gray">Leer más ...</a>
                <a href="#" class="cl-effect-1 color-pink">Leer más ...</a>
                <a href="#" class="cl-effect-1 color-red">Leer más ...</a>
              </div>

              <div class="text-center">
                <h3>Efecto 14 (.cl-effect-14)</h3>
                <p><a href="#" class="cl-effect-14 bg-blue color-blue"><span>Leer Más</span></a></p>
                <p><a href="#" class="cl-effect-14 bg-green color-green"><span>Leer Más</span></a></p>
                <p><a href="#" class="cl-effect-14 bg-gray color-gray"><span>Leer Más</span></a></p>
                <p><a href="#" class="cl-effect-14 bg-pink color-pink"><span>Leer Más</span></a></p>
                <p><a href="#" class="cl-effect-14 bg-red color-red"><span>Leer Más</span></a></p>
              </div>
            </div>

            <!-- Columna 2 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 5 (.cl-effect-5)</h3>
                <p><a href="#" class="cl-effect-5 color-blue"><span data-hover="Mostrar">Mostrar</span></a></p>
                <p><a href="#" class="cl-effect-5 color-green"><span data-hover="Mostrar">Mostrar</span></a></p>
                <p><a href="#" class="cl-effect-5 color-gray"><span data-hover="Mostrar">Mostrar</span></a></p>
                <p><a href="#" class="cl-effect-5 color-pink"><span data-hover="Mostrar">Mostrar</span></a></p>
                <p><a href="#" class="cl-effect-5 color-red"><span data-hover="Mostrar">Mostrar</span></a></p>
              </div>

              <div class="text-center">
                <h3>Efecto 18 (.cl-effect-18)</h3>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-18 bg-blue"><span>Enlace</span></a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-18 bg-green"><span>Enlace</span></a></p
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-18 bg-gray"><span>Enlace</span></a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-18 bg-pink"><span>Enlace</span></a></p
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-18 bg-red"><span>Enlace</span></a></p>
              </div>
            </div>

            <!-- Columna 3 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 7 (.cl-effect-5)</h3>
                <p><a href="#" class="cl-effect-7 color-blue bg-blue">Leer Más</a></p>
                <p><a href="#" class="cl-effect-7 color-green bg-green">Leer Más</a></p>
                <p><a href="#" class="cl-effect-7 color-gray bg-gray">Leer Más</a></p>
                <p><a href="#" class="cl-effect-7 color-pink bg-pink">Leer Más</a></p>
                <p><a href="#" class="cl-effect-7 color-red bg-red">Leer Más</a></p>
              </div>

              <div class="text-center">
                <h3>Efecto 21 (.cl-effect-21)</h3>
                <p><a href="#" class="cl-effect-21 color-blue bg-blue">Leer Más</a></p>
                <p><a href="#" class="cl-effect-21 color-green bg-green">Leer Más</a></p>
                <p><a href="#" class="cl-effect-21 color-gray bg-gray">Leer Más</a></p>
                <p><a href="#" class="cl-effect-21 color-pink bg-pink">Leer Más</a></p>
                <p><a href="#" class="cl-effect-21 color-red bg-red">Leer Más</a></p>
              </div>
            </div>

            <!-- Columna 4 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 10 (.cl-effect-10)</h3>
                <a href="#" class="cl-effect-10 cl-10-blue" data-hover="Continuar"><span>Continuar</span></a>
                <a href="#" class="cl-effect-10 cl-10-green" data-hover="CONTINUAR"><span>Continuar</span></a>
                <a href="#" class="cl-effect-10 cl-10-gray" data-hover="Continuar"><span>Continuar</span></a>
                <a href="#" class="cl-effect-10 cl-10-pink" data-hover="CONTINUAR"><span>Continuar</span></a>
                <a href="#" class="cl-effect-10 cl-10-red" data-hover="Continuar"><span>Continuar</span></a>
              </div>
            </div>

            <!-- Columna 5 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 12 (.cl-effect-12)</h3>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-12 cl-12-blue color-blue">Continuar</a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-12 cl-12-green color-green">Continuar</a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-12 cl-12-gray color-gray">Continuar</a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-12 cl-12-pink color-pink">Continuar</a></p>
                <p>&nbsp;</p>
                <p><a href="#" class="cl-effect-12 cl-12-red color-red">Continuar</a></p>
              </div>
            </div>

            <!-- Columna 6 -->
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class="text-center">
                <h3>Efecto 13 (.cl-effect-13)</h3>
                <p><a href="#" class="cl-effect-13 color-blue"><span>Continuar</span></a></p>
                <p><a href="#" class="cl-effect-13 color-green"><span>CONTINUAR</span></a></p>
                <p><a href="#" class="cl-effect-13 color-gray"><span>Continuar</span></a></p>
                <p><a href="#" class="cl-effect-13 color-pink"><span>CONTINUAR</span></a></p>
                <p><a href="#" class="cl-effect-13 color-red"><span>Continuar</span></a></p>
              </div>
            </div>

          </div>

        </div>

    </div>
</div>

app/views/themes/index.html.erb
<!-- Navbar -->
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
  <%= render 'sidebar_theme' %>
</div>

<!-- Content -->
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
  <div class="bg-white"><p>Basic template</p></div>
</div>

app/views/themes/tipo.html.erb
<!-- Navbar -->
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
  <%= render 'sidebar_theme' %>
</div>

<!-- Content -->
<div class="col-lg-9 col-md-9 col-sm-6 col-xs-12">
  <div class="bg-white">

    <div class="encabezado text-center">Encabezados</div>

    <div class="container-fluid">
    	<div class="row">


    		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    			<h1>Subtitulos - H1 30px</h1>
          <p class="text-left">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>

          <h2>Subtitulos - H2 18px</h2>
          <p class="text-center">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>

    		</div>


    		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    			<h3>Subtitulos - H3 14px</h3>
          <p class="text-right">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>

    			<h4>Justificado 14px</h4>
    			<p class="text-justify">
    				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    			</p>
    		</div>

    	</div>
    </div>

  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>