config/routes.rb
Rails.application.routes.draw do

  get 'post/index'

  namespace :admin do
    resources :categories
    resources :labels
    resources :posts
    resources :home, only: [:index]
  end

  devise_for :users
  get 'themes/tipo'
  get 'themes/buttons'
  get 'themes/form'
  get 'themes/hyperlink'
  get 'themes/index'
  # You can have the root of your site routed with "root"
  root 'home#index'

  resources :posts, only: [:show] do
    resources :comments, only: [:create]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :nombre_categoria, presence: true
  validates :nombre_categoria, uniqueness: true

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :category
  has_many :posts, through: :post_has_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :comentario, presence: true
    belongs_to :posts
end

app/models/label.rb
class Label < ActiveRecord::Base
  validates :nombre_etiqueta, presence: true
  validates :nombre_etiqueta, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :titulo,:contenido, presence: true
  validates :titulo,:contenido, uniqueness: true

  belongs_to :user

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :post
  has_many :categories, through: :post_has_categories

  has_many :comments, dependent: :destroy
end

app/models/post_has_category.rb
class PostHasCategory < ActiveRecord::Base
  belongs_to :post, :inverse_of => :post_has_categories
  belongs_to :category, :inverse_of => :post_has_categories

  validates_presence_of :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  validates :nombre, presence: true
  validates :apellidoPaterno, presence: true
  validates :apellidoMaterno, presence: true

  has_many :posts

  def nombre_usuario
    "#{nombre} #{apellidoPaterno} #{apellidoMaterno}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
        params.require(:comment).permit(:nombre_completo, :comentario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :set_categories

  def tipo
  end

  def form
  end

  def buttons
  end

  def hyperlink
  end

  private
    def set_categories
      @categories = Category.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def label_params
      params.require(:user).permit(:nombre, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML

    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
    <ul> LOOKS LIKE THAT YOU WAS WRONG IN SOME FIELD :(  </ul>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/admin/_navbar.html.erb
<nav class="admin navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to '<img style="width: 64px;" src="/images/admin/spartan-logo.png">Spartans'.html_safe, root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a><%=  current_user.nombre_usuario %></a></li>
        <li><%= link_to '<i class="fa fa-lock"></i>&nbsp;Cerrar Sesión'.html_safe, destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div class="admin-sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li <%= 'class=active' if params[:controller] == 'admin/categories' %> >
      <%= link_to "Categorías", admin_categories_path %>
    </li>
    <li <%= 'class=active' if params[:controller] == 'admin/labels' %> >
      <%= link_to "Etiquetas", admin_labels_path %>
    </li>
    <li <%= 'class=active' if params[:controller] == 'admin/posts' %> >
      <%= link_to "Posts", admin_posts_path %>
    </li>
  </ul>
</div>

app/views/layouts/partials/_banner.html.erb
<div class="banner-style1">
	<div class="col-lg-4 col-md-4 col-sm-3 col-xs-3">
		<p class="title-blog"> Spartan Class </p>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
		<div class="spartan-logo">
			<img src="/images/spartan1.png" class="border-radius50">
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-3 col-xs-3">
		<p class="leyenda"> Divide y Venceras</p> 
	</div>
</div>

app/views/layouts/partials/_footer.html.erb
<footer>
	<div class="pull-left">Derechos reservados © <strong><%= link_to "team-sparta", new_user_session_path, class: "colorfooter"%></strong> 2016 </div>
	<div class="pull-right">Version 0.1</div>
	<div class="clearfix"></div>
</footer>

app/views/layouts/partials/_navbar.html.erb
<div class="blog-navbar">
    <ul class="topnav" id="responsive-mode-on">
        <%= link_to '<img id="spartan-radio" src="/images/spartan_image.jpg"/>'.html_safe, root_path %>
        <div class="tittle-blog">Spartans</div>
        <li>
          <div class="search-label">
            <label class="search-logo"><i class="fa fa-search"></i></label>
            <input id="search-input" class="form-control"  placeholder="Buscar...">
          </div>
        </li>
        <li>
          <div class="dropdown">
            <button type="submit" class="dropbtn">Categorias</button>
              <div class="dropdown-content">
              <% @categories.each do |item| %>
                <a href="#"> <%= item.nombre_categoria %></a>
              <% end %>
              </div>
          </div>
        </li>
        <li>
            <a href="#contact">Contacto</a>
        </li>
        <li>
            <a href="#news">Inicio</a>
        </li>
        <li class="icon">
          <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
        </li>
    </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <b>Alerta !! </b><%= object.errors.count > 1 ? "Se han encontrado #{object.errors.count} errores:": "Se ha encontrado #{object.errors.count} error:" %>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_notice_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <b>Información !!</b> <%= notice %>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <b>Alerta !!</b> <%= alert %>
  </div>
<% end %>