config/routes.rb
Rails.application.routes.draw do

  get 'post/index'

  namespace :admin do
    resources :categories
    resources :labels
    resources :posts
    resources :home, only: [:index]
  end

  devise_for :users
  get 'themes/tipo'
  get 'themes/buttons'
  get 'themes/form'
  get 'themes/hyperlink'
  get 'themes/index'
  # You can have the root of your site routed with "root"
  root 'home#index'

  resources :posts, only: [:show] do
    resources :comments, only: [:create]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :nombre_categoria, presence: true
  validates :nombre_categoria, uniqueness: true

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :category
  has_many :posts, through: :post_has_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validates :comentario, presence: true
    belongs_to :posts
end

app/models/label.rb
class Label < ActiveRecord::Base
  validates :nombre_etiqueta, presence: true
  validates :nombre_etiqueta, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :titulo,:contenido, presence: true
  validates :titulo,:contenido, uniqueness: true

  belongs_to :user

  has_many :post_has_categories, :dependent => :destroy, :autosave => true , :inverse_of => :post
  has_many :categories, through: :post_has_categories

  has_many :comments, dependent: :destroy
end

app/models/post_has_category.rb
class PostHasCategory < ActiveRecord::Base
  belongs_to :post, :inverse_of => :post_has_categories
  belongs_to :category, :inverse_of => :post_has_categories

  validates_presence_of :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  validates :nombre, presence: true
  validates :apellidoPaterno, presence: true
  validates :apellidoMaterno, presence: true

  has_many :posts

  def nombre_usuario
    "#{nombre} #{apellidoPaterno} #{apellidoMaterno}"
  end
end

app/controllers/admin/labels_controller.rb
module Admin
  class LabelsController < ApplicationController

    before_filter :authenticate_user!
    before_action :set_label, only: [:edit, :show, :update, :destroy]
    layout 'adminterface'

    def index
      @labels = Label.all
    end

    def new
      @label = Label.new
    end

    def create
      @label = Label.new(label_params)
      respond_to do |format|
        if @label.save
          format.html { redirect_to [ "admin", @label ], notice: 'Label creado' }
        else
          format.html { render :new }
        end
      end
    end

    def edit
    end

    def show
    end

    def update
      respond_to do |format|
        if @label.update(label_params)
          format.html { redirect_to [ "admin", @label ], notice: 'El label ha sido actualizado' }
        else
          format.html { render :new }
        end
      end
    end

    def destroy
      respond_to do |format|
        if @label.destroy
          format.html { redirect_to admin_labels_url, notice: "Elemento eliminado" }
        else
          format.html { render :index, notice: "Elemento no eliminado" }
        end
      end
    end

    private
      def label_params
        params.require(:label).permit(:nombre_etiqueta)
      end

      def set_label
        @label = Label.find(params[:id])
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource
  private
    def after_sign_in_path_for(resourse)
        admin_home_index_path
    end

  protected
    def layout_by_resource
      if devise_controller?
        "login"
      else
        "application"
      end
    end
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :email, :password, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento] )
        devise_parameter_sanitizer.permit(:sign_in, keys: [:nombre, :email, :password, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento] )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
        params.require(:comment).permit(:nombre_completo, :comentario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :set_categories

  def tipo
  end

  def form
  end

  def buttons
  end

  def hyperlink
  end

  private
    def set_categories
      @categories = Category.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def label_params
      params.require(:user).permit(:nombre, :apellidoPaterno, :apellidoMaterno, :fechaNacimiento)
    end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML

    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
    <ul> LOOKS LIKE THAT YOU WAS WRONG IN SOME FIELD :(  </ul>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/admin/labels/_form.html.erb
<%= render 'shared/error_messages', object: @label %>

<%= form_for(['admin', @label], html: { class: 'form-horizontal' }) do |f| %>
    <fieldset>
        <legend>Registro</legend>

        <div class="form-group">
            <%= f.label :nombre_etiqueta, class: "col-lg-3 col-md-4 col-sm-4 col-xs-6 control-label" %>
            <div class="col-lg-9 col-md-8 col-sm-8 col-xs-6">
                <%= f.text_field :nombre_etiqueta, autofocus: true, :class => 'form-control' %>
            </div>
        </div>

        <div class="pull-left">
            <%= link_to "Regresar", admin_labels_path, class: "btn btn-default" %>
            <% if params[:action] == 'edit' %>
                <%= link_to "Eliminar", admin_label_path(@label), method: :delete, data: { confirm: "x" }, class: "btn btn-danger" %>
            <% end %>
        </div>
        <div class="pull-right">
            <%= f.submit nil, class: "btn btn-primary" %>
        </div>
        <div class="clearfix"></div>

    </fieldset>

<% end %>

app/views/admin/labels/index.html.erb
<p><%= link_to "Nuevo label", new_admin_label_path, class: "btn btn-primary" %></p>
<% if @labels.blank? %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Información!</strong> Aun no hay elementos en la base de datos.
  </div>
<% else %>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Label</th>
          <th width="200px">Opciones</th>
        </tr>
      </thead>
      <tbody>
        <% @labels.each do |item| %>
        <tr>
          <td><%= item.nombre_etiqueta %></td>
          <td class="text-center">
            <%= link_to "Mostar", admin_label_path(item), class: "btn btn-xs btn-info" %>
            <%= link_to "Editar", edit_admin_label_path(item), class: "btn btn-xs btn-success" %>
            <%= link_to "Eliminar", admin_label_path(item), method: :delete, data: { confirm: 'Estas seguro de eliminar el elemento?' }, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>

<% end %>

app/views/admin/labels/new.html.erb
<%= render "form" %>

app/views/admin/labels/show.html.erb
<p><%= link_to "Nuevo label", new_admin_label_path, class: "btn btn-primary" %></p>

<%= render 'shared/notice_messages' %>

<table class="table">
  <tr>
    <th>Label</th>
    <td><%= @label.nombre_etiqueta %></td>
  </tr>
</table>

<div class="pull-left">
    <%= link_to "Regresar", admin_labels_path, class: "btn btn-default" %>
    <%= link_to "Editar", edit_admin_label_path(@label), class: "btn btn-success" %>
    <%= link_to "Eliminar", admin_label_path(@label), method: :delete, data: { confirm: 'Estas seguro de eliminar el elemento?' }, class: "btn btn-danger"%>
</div>
<div class="clearfix"></div>